### ISSUE TITLE
GetDevicesInFirstStructureAsync - System.IO.DirectoryNotFoundException:

### ISSUE THREAD

**Issue by toby11** [jimmyjudas/LightwaveRFLinkPlusSharp#6]
on using GetDevicesInFirstStructureAsync  I get this exception ?

System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\Users\xxx\AppData\Roaming\LightwaveRFLinkPlusSharp\auth_response.txt'.'

not sure why its even trying to write to disk to auth?!

**Comment by jimmyjudas** [comment]
It writes the refresh and access tokens that are returned from Lightwave to disk so that it has access to them the next time the program starts. Otherwise you'd have to manually get a new one from Lightwave each time you restarted.

I have a feeling I know what's going wrong here. Can you try creating a folder called LightwaveRFLinkPlusSharp in C:\Users\xxx\AppData\Roaming and see if it that fixes it?

**Comment by toby11** [comment]
yes after creating that directory it all works fine now. thanks!

I would maybe put a note in the readme.md to say it will write the token to disk.

**Comment by jimmyjudas** [comment]
Sorry for not replying sooner but glad that got it working for you. I've updated the code to handle creating the folder if it doesn't already exist. I've pushed a new version of the nuget package too. Thanks for the bug report!
